export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const START_AUTH_LOADING = 'START_AUTH_LOADING';
export const STOP_AUTH_LOADING = 'STOP_AUTH_LOADING';
export const SIGNUP = 'SIGNUP';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_FAILED = 'LOAD_USER_FAILED';
export const LOGOUT = 'LOGOUT';

export const GET_COMPANIES = 'GET_COMPANIES';
export const START_COMPANY_LOADING = 'START_COMPANY_LOADING';
export const STOP_COMPANY_LOADING = 'STOP_COMPANY_LOADING';
export const EDIT_COMPANY = 'EDIT_COMPANY';
export const ADD_COMPANY = 'ADD_COMPANY';
export const COMPANY_ERROR = 'COMPANY_ERROR';
export const SEARCH_COMPANY = 'SEARCH_COMPANY';

export const EDIT_CONTACT = 'EDIT_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';

export const GET_REPORTS = 'GET_REPORTS';
export const ADD_REPORT = 'ADD_REPORT';
export const EDIT_REPORT = 'EDIT_REPORT';
export const GET_REPORTS_TYPES = 'GET_REPORTS_TYPES';
export const ADD_REPORT_TYPE = 'ADD_REPORT_TYPE';
export const START_REPORTS_LOADING = 'START_REPORTS_LOADING';
export const STOP_REPORTS_LOADING = 'STOP_REPORTS_LOADING';
export const GET_MACHINES = 'GET_MACHINES';

export const GET_LOGS = 'GET_LOGS';
export const START_LOGS_LOADING = 'START_LOGS_LOADING';
export const STOP_LOGS_LOADING = 'STOP_LOGS_LOADING';

export const GET_USERS = 'GET_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const START_USERS_LOADING = 'START_USERS_LOADING';
export const STOP_USERS_LOADING = 'STOP_USERS_LOADING';
export const TOGGLE_BLOCK = 'TOGGLE_BLOCK';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const START_NOTIFICATIONS_LOADING = 'START_NOTIFICATIONS_LOADING';
export const STOP_NOTIFICATIONS_LOADING = 'STOP_NOTIFICATIONS_LOADING';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';
export const SEND_NOTIFICATION = 'SEND_NOTIFICATION';

export const ICOUNT_LOGIN = 'ICOUNT_LOGIN';
export const GET_ICOUNT_CLIENTS = 'GET_ICOUNT_CLIENTS';
export const START_ICOUNT_LOADING = 'START_ICOUNT_LOADING';
export const STOP_ICOUNT_LOADING = 'STOP_ICOUNT_LOADING';
